[package]
name = "regex-engine"
version = "1.0.1"
description = "A verified, linear-time JavaScript regular-expression matcher (RegElk) in Dafny"
repository = "https://github.com/hath995/Linden-Dafny/tree/main/regex-engine"
license = "MIT"
keywords = ["regular expression", "Finite Automata", "PikeVM"]

[toolchain]
dafny = ">= 4.11.0"

[source]
to_export = ["src/**/*.dfy"]

[options]
standard-libraries = true

[verification]
expected-errors = [
]

[dependencies]

[test.dependencies]
dafnycheck = "^1.0.0"
