// OCaml-vs-Dafny cross-check over the full bug-regression corpus from tests.ml.
//
// Every (raw_regex, string) case from tests.ml's regression lists (the inputs
// that exposed real bugs during the OCaml engine's development, many found by
// fuzzer.ml) is replayed here. The expected arrays are the RAW outputs of the
// ORIGINAL OCaml RegElk engine (opam `linden` switch, OCaml 4.14.2), captured by
// gen_dafny.ml -> Interpreter(Map_Regs).full_match, INCLUDING register quirks
// (reversed lookbehind capture spans, stale end registers). Asserting all three
// Dafny register engines reproduce them pins bit-for-bit fidelity to the OCaml.
// AUTO-GENERATED block below (gen_dafny.ml); do not edit by hand.
module OCamlBugRegressions {
  import opened Std.Wrappers
  import opened Charclasses
  import opened RegElkRegex
  import AI = ArrayInterp
  import LI = ListInterp
  import MI = MapInterp

  method checkAll(raw: raw_regex, s: string, ocaml: Option<seq<int>>) {
    var a := AI.full_match(raw, s);
    var l := LI.full_match(raw, s);
    var m := MI.full_match(raw, s);
    expect a == ocaml, "Array_Regs != OCaml";
    expect l == ocaml, "List_Regs != OCaml";
    expect m == ocaml, "Map_Regs != OCaml";
  }

  method {:test} ocaml_bug_regressions() {
    // string_sub_errors
    checkAll(Raw_lookaround(Lookbehind, Raw_capture(Raw_character(Dot))), "bababaaabbacacbabbacabcccaaacaabccab", Some([1, 1, 1, 0]));
    checkAll(Raw_lookaround(Lookbehind, Raw_capture(Raw_con(Raw_capture(Raw_capture(Raw_alt(Raw_empty, Raw_lookaround(Lookbehind, Raw_lookaround(NegLookahead, Raw_quant(LazyStar, Raw_alt(Raw_lookaround(NegLookahead, Raw_character(Dot)), Raw_capture(Raw_character(Dot))))))))), Raw_lookaround(Lookbehind, Raw_capture(Raw_character(Dot)))))), "bcacaaaacaabcbbcacaaacbbaabc", Some([1, 1, 1, 1, 1, 1, 1, 1, -1, -1, 1, 0]));
    checkAll(Raw_lookaround(Lookbehind, Raw_capture(Raw_character(Dot))), "cabacbbccbacbcbbccbaccbaccabbbaaa", Some([1, 1, 1, 0]));
    checkAll(Raw_lookaround(Lookbehind, Raw_capture(Raw_capture(Raw_character(Dot)))), "bbacccabbcccbcccaabcbabcaaacacacbbbcabbc", Some([1, 1, 1, 0, 1, 0]));
    // oracle_assert_errors
    checkAll(Raw_con(Raw_lookaround(Lookbehind, Raw_empty), Raw_lookaround(Lookbehind, Raw_lookaround(Lookbehind, Raw_character(Char('a'))))), "ccbba", Some([5, 5]));
    // expected_result_oracle_errors
    checkAll(Raw_lookaround(Lookbehind, Raw_character(Char('b'))), "bccaaacabcbcabaacbccaccbbbaaccccaabcac", Some([1, 1]));
    checkAll(Raw_lookaround(Lookbehind, Raw_character(Char('a'))), "cabbcabcccacbbabcb", Some([2, 2]));
    // idk
    checkAll(Raw_capture(Raw_con(Raw_con(Raw_lookaround(Lookbehind, Raw_lookaround(Lookbehind, Raw_alt(Raw_alt(Raw_character(Char('b')), Raw_capture(Raw_empty)), Raw_character(Char('a'))))), Raw_quant(Star, Raw_lookaround(NegLookbehind, Raw_capture(Raw_lookaround(NegLookahead, Raw_lookaround(NegLookbehind, Raw_lookaround(NegLookahead, Raw_character(Char('c'))))))))), Raw_quant(Plus, Raw_con(Raw_character(Dot), Raw_empty)))), "babcbcaacccbbcccabacaccaaccbabcbbbabbabbbabbcbcaa", Some([0, 49, 0, 49, 0, 0, -1, -1]));
    // clear_mem
    checkAll(Raw_quant(Star, Raw_alt(Raw_con(Raw_character(Char('a')), Raw_lookaround(Lookahead, Raw_capture(Raw_character(Char('b'))))), Raw_character(Char('b')))), "abc", Some([0, 2, -1, 2]));
    // empty_problem
    checkAll(Raw_con(Raw_lookaround(NegLookbehind, Raw_character(Char('b'))), Raw_quant(Plus, Raw_alt(Raw_empty, Raw_capture(Raw_character(Dot))))), "bbccbacbccbcabbcbcaccccba", Some([0, 25, 24, 25]));
    checkAll(Raw_quant(Plus, Raw_alt(Raw_empty, Raw_con(Raw_alt(Raw_character(Dot), Raw_alt(Raw_character(Dot), Raw_empty)), Raw_alt(Raw_lookaround(Lookahead, Raw_character(Char('b'))), Raw_quant(LazyStar, Raw_capture(Raw_lookaround(Lookbehind, Raw_alt(Raw_capture(Raw_empty), Raw_lookaround(NegLookbehind, Raw_lookaround(NegLookahead, Raw_con(Raw_con(Raw_character(Dot), Raw_capture(Raw_character(Dot))), Raw_lookaround(Lookbehind, Raw_lookaround(Lookbehind, Raw_capture(Raw_quant(LazyStar, Raw_empty))))))))))))))), "bbccaaccbbbaccabccbabccababc", Some([0, 28, -1, -1, -1, -1, -1, -1, -1, -1]));
    checkAll(Raw_alt(Raw_quant(Plus, Raw_alt(Raw_empty, Raw_character(Dot))), Raw_capture(Raw_alt(Raw_character(Dot), Raw_character(Char('c'))))), "bbccacccabcbaaabbabbbccccccacbaabacbc", Some([0, 37, -1, -1]));
    // double_quant
    checkAll(Raw_quant(Plus, Raw_alt(Raw_quant(LazyStar, Raw_lookaround(NegLookbehind, Raw_con(Raw_lookaround(NegLookbehind, Raw_lookaround(NegLookbehind, Raw_alt(Raw_character(Char('c')), Raw_character(Char('c'))))), Raw_lookaround(NegLookbehind, Raw_quant(Plus, Raw_character(Dot)))))), Raw_character(Dot))), "abacaaaacabaccbcabcacabccbcaacbabaa", Some([0, 35]));
    checkAll(Raw_capture(Raw_quant(Plus, Raw_quant(LazyStar, Raw_character(Dot)))), "bacababaacbcabaabccccacca", Some([0, 25, 0, 25]));
    checkAll(Raw_con(Raw_con(Raw_empty, Raw_capture(Raw_quant(Star, Raw_quant(LazyStar, Raw_character(Dot))))), Raw_character(Dot)), "abcbbca", Some([0, 7, 0, 6]));
    // empty_group
    checkAll(Raw_quant(Star, Raw_alt(Raw_con(Raw_character(Char('a')), Raw_capture(Raw_empty)), Raw_character(Char('b')))), "ab", Some([0, 2, -1, 1]));
    // should_not_clear
    checkAll(Raw_alt(Raw_con(Raw_quant(LazyStar, Raw_alt(Raw_capture(Raw_con(Raw_quant(Star, Raw_lookaround(Lookahead, Raw_empty)), Raw_empty)), Raw_capture(Raw_empty))), Raw_character(Char('a'))), Raw_empty), "cbacacaabbcbaacbbababcbcaaa", Some([0, 0, -1, -1, -1, -1]));
    checkAll(Raw_alt(Raw_con(Raw_alt(Raw_empty, Raw_lookaround(NegLookbehind, Raw_lookaround(Lookbehind, Raw_quant(LazyPlus, Raw_character(Char('b')))))), Raw_lookaround(Lookahead, Raw_character(Char('b')))), Raw_quant(LazyStar, Raw_character(Char('c')))), "cbcaaaacccabbaacccaacbcbacbbabcaccbbbbc", Some([0, 0]));
    checkAll(Raw_con(Raw_capture(Raw_capture(Raw_con(Raw_con(Raw_alt(Raw_capture(Raw_con(Raw_alt(Raw_quant(LazyStar, Raw_character(Dot)), Raw_capture(Raw_lookaround(NegLookbehind, Raw_capture(Raw_lookaround(NegLookahead, Raw_character(Char('c'))))))), Raw_capture(Raw_character(Char('b'))))), Raw_quant(Plus, Raw_con(Raw_character(Char('a')), Raw_alt(Raw_con(Raw_lookaround(NegLookbehind, Raw_lookaround(Lookbehind, Raw_capture(Raw_character(Dot)))), Raw_empty), Raw_con(Raw_capture(Raw_lookaround(NegLookbehind, Raw_quant(LazyStar, Raw_character(Dot)))), Raw_character(Char('a'))))))), Raw_character(Char('b'))), Raw_con(Raw_con(Raw_con(Raw_character(Dot), Raw_character(Dot)), Raw_lookaround(NegLookahead, Raw_capture(Raw_character(Char('c'))))), Raw_capture(Raw_con(Raw_capture(Raw_character(Dot)), Raw_character(Dot))))))), Raw_alt(Raw_con(Raw_alt(Raw_lookaround(NegLookbehind, Raw_alt(Raw_character(Char('a')), Raw_empty)), Raw_quant(LazyPlus, Raw_empty)), Raw_lookaround(NegLookbehind, Raw_lookaround(NegLookbehind, Raw_lookaround(NegLookahead, Raw_lookaround(NegLookahead, Raw_con(Raw_con(Raw_lookaround(Lookahead, Raw_character(Char('c'))), Raw_lookaround(NegLookbehind, Raw_capture(Raw_alt(Raw_capture(Raw_empty), Raw_lookaround(NegLookbehind, Raw_character(Char('b'))))))), Raw_character(Char('a')))))))), Raw_empty)), "cabababbccaaccbabbaaacbb", Some([0, 12, 0, 12, 0, 12, 0, 7, -1, -1, -1, -1, 6, 7, -1, -1, -1, -1, -1, -1, 10, 12, 10, 11, -1, -1, -1, -1]));
    checkAll(Raw_capture(Raw_capture(Raw_quant(Plus, Raw_capture(Raw_con(Raw_con(Raw_quant(LazyPlus, Raw_lookaround(Lookbehind, Raw_lookaround(NegLookbehind, Raw_character(Char('b'))))), Raw_con(Raw_character(Char('c')), Raw_empty)), Raw_capture(Raw_alt(Raw_con(Raw_quant(LazyPlus, Raw_empty), Raw_capture(Raw_capture(Raw_quant(LazyPlus, Raw_empty)))), Raw_capture(Raw_character(Dot))))))))), "ccbbbccababcababbbaccabccbacababbacbcababcabbaccccacbccbbbcbbcbcacacbaaacaaababccbbbbbbac", Some([0, 2, 0, 2, 0, 2, 1, 2, 2, 2, 2, 2, 2, 2, -1, -1]));
    // empty_repetitions
    checkAll(Raw_quant(Plus, Raw_con(Raw_alt(Raw_character(Char('a')), Raw_empty), Raw_quant(LazyStar, Raw_capture(Raw_character(Dot))))), "bab", Some([0, 3, 2, 3]));
    checkAll(Raw_quant(Star, Raw_con(Raw_alt(Raw_character(Char('a')), Raw_empty), Raw_quant(LazyStar, Raw_character(Dot)))), "ab", Some([0, 2]));
    checkAll(Raw_quant(Star, Raw_con(Raw_alt(Raw_character(Char('a')), Raw_empty), Raw_alt(Raw_empty, Raw_character(Char('b'))))), "ab", Some([0, 2]));
    // linear_stuck
    checkAll(Raw_con(Raw_lookaround(Lookbehind, Raw_empty), Raw_capture(Raw_con(Raw_character(Dot), Raw_quant(Plus, Raw_capture(Raw_con(Raw_lookaround(NegLookbehind, Raw_quant(LazyPlus, Raw_quant(LazyPlus, Raw_quant(LazyPlus, Raw_capture(Raw_alt(Raw_capture(Raw_alt(Raw_alt(Raw_character(Dot), Raw_alt(Raw_lookaround(NegLookbehind, Raw_alt(Raw_empty, Raw_capture(Raw_empty))), Raw_con(Raw_alt(Raw_capture(Raw_character(Dot)), Raw_capture(Raw_character(Char('b')))), Raw_empty))), Raw_quant(LazyStar, Raw_capture(Raw_con(Raw_empty, Raw_alt(Raw_capture(Raw_quant(Plus, Raw_capture(Raw_capture(Raw_capture(Raw_con(Raw_alt(Raw_empty, Raw_empty), Raw_capture(Raw_capture(Raw_con(Raw_capture(Raw_lookaround(Lookahead, Raw_lookaround(NegLookbehind, Raw_empty))), Raw_con(Raw_quant(Star, Raw_capture(Raw_con(Raw_alt(Raw_empty, Raw_capture(Raw_alt(Raw_capture(Raw_quant(LazyPlus, Raw_empty)), Raw_alt(Raw_capture(Raw_character(Char('a'))), Raw_character(Dot))))), Raw_alt(Raw_character(Char('c')), Raw_empty)))), Raw_character(Char('b')))))))))))), Raw_con(Raw_lookaround(NegLookbehind, Raw_capture(Raw_quant(Star, Raw_lookaround(NegLookbehind, Raw_lookaround(Lookahead, Raw_con(Raw_capture(Raw_lookaround(Lookahead, Raw_lookaround(NegLookbehind, Raw_lookaround(Lookahead, Raw_empty)))), Raw_character(Dot))))))), Raw_empty))))))), Raw_lookaround(NegLookahead, Raw_empty))))))), Raw_empty)))))), "cbacaaaababbcaaaaababcabcabaccaaaacb", None);
    // linear_plus
    checkAll(Raw_alt(Raw_lookaround(NegLookbehind, Raw_capture(Raw_capture(Raw_con(Raw_quant(Star, Raw_empty), Raw_capture(Raw_quant(Plus, Raw_alt(Raw_capture(Raw_empty), Raw_lookaround(NegLookbehind, Raw_capture(Raw_capture(Raw_con(Raw_capture(Raw_lookaround(Lookbehind, Raw_alt(Raw_capture(Raw_quant(LazyStar, Raw_alt(Raw_lookaround(Lookbehind, Raw_con(Raw_character(Char('c')), Raw_character(Dot))), Raw_character(Dot)))), Raw_empty))), Raw_quant(Star, Raw_lookaround(Lookahead, Raw_lookaround(Lookbehind, Raw_lookaround(Lookbehind, Raw_capture(Raw_con(Raw_quant(LazyStar, Raw_quant(LazyPlus, Raw_empty)), Raw_quant(LazyStar, Raw_capture(Raw_capture(Raw_empty)))))))))))))))))))), Raw_capture(Raw_empty)), "bacabacbcabcaacac", Some([0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0]));
    checkAll(Raw_quant(Plus, Raw_con(Raw_capture(Raw_lookaround(Lookbehind, Raw_alt(Raw_con(Raw_character(Char('b')), Raw_empty), Raw_capture(Raw_empty)))), Raw_empty)), "bbacaaaaccbcaaccaacaaababacccbcbbbccbccb", Some([0, 0, 0, 0, 0, 0]));
    checkAll(Raw_quant(Plus, Raw_lookaround(Lookbehind, Raw_alt(Raw_character(Dot), Raw_capture(Raw_empty)))), "b", Some([0, 0, 0, 0]));
    checkAll(Raw_alt(Raw_lookaround(Lookahead, Raw_lookaround(NegLookbehind, Raw_lookaround(NegLookahead, Raw_con(Raw_lookaround(NegLookahead, Raw_capture(Raw_empty)), Raw_lookaround(Lookahead, Raw_capture(Raw_character(Dot))))))), Raw_lookaround(Lookahead, Raw_con(Raw_capture(Raw_alt(Raw_quant(Star, Raw_capture(Raw_con(Raw_alt(Raw_lookaround(Lookahead, Raw_character(Char('b'))), Raw_lookaround(Lookahead, Raw_character(Char('c')))), Raw_capture(Raw_alt(Raw_lookaround(NegLookbehind, Raw_alt(Raw_lookaround(Lookbehind, Raw_character(Char('c'))), Raw_character(Char('c')))), Raw_capture(Raw_con(Raw_character(Dot), Raw_character(Dot)))))))), Raw_con(Raw_character(Dot), Raw_alt(Raw_character(Dot), Raw_character(Char('b')))))), Raw_quant(Star, Raw_con(Raw_quant(Plus, Raw_capture(Raw_lookaround(NegLookbehind, Raw_character(Char('b'))))), Raw_quant(Star, Raw_con(Raw_character(Dot), Raw_character(Dot)))))))), "accababbbabbccacabcaccaabcbbabcaaacbaaccabacababa", Some([0, 0, -1, -1, -1, -1, 0, 0, -1, -1, -1, -1, -1, -1, 0, 0]));
    // plus_reconstruct
    checkAll(Raw_con(Raw_quant(Plus, Raw_capture(Raw_empty)), Raw_character(Char('a'))), "a", Some([0, 1, 0, 0]));
    checkAll(Raw_quant(Plus, Raw_alt(Raw_con(Raw_lookaround(Lookbehind, Raw_lookaround(NegLookahead, Raw_empty)), Raw_capture(Raw_character(Char('b')))), Raw_alt(Raw_alt(Raw_lookaround(Lookahead, Raw_capture(Raw_alt(Raw_empty, Raw_character(Dot)))), Raw_alt(Raw_lookaround(NegLookbehind, Raw_character(Dot)), Raw_empty)), Raw_character(Char('c'))))), "babcaccbbabcacacabcaaaababbccaccccbabbcabccbbbcaacbbababccabacbbbabcbacbaabcbbccbabbccbaa", Some([0, 0, -1, -1, 0, 0]));
    checkAll(Raw_quant(LazyPlus, Raw_con(Raw_quant(LazyPlus, Raw_capture(Raw_character(Dot))), Raw_con(Raw_alt(Raw_quant(Plus, Raw_capture(Raw_empty)), Raw_quant(Star, Raw_quant(Star, Raw_character(Char('c'))))), Raw_alt(Raw_lookaround(NegLookbehind, Raw_empty), Raw_alt(Raw_capture(Raw_capture(Raw_empty)), Raw_character(Char('c'))))))), "abaabaccbcabaccabaacabccabbccacbbccbcbacabaacbaaacbacabbaacabaccabaacbbbbccaccaacaacabccccba", Some([0, 1, 0, 1, 1, 1, 1, 1, 1, 1]));
    checkAll(Raw_quant(Plus, Raw_capture(Raw_capture(Raw_capture(Raw_capture(Raw_con(Raw_empty, Raw_empty)))))), "cccccacaccbccabbcabacbaacacabcacbbabcbcccacbcab", Some([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]));
    checkAll(Raw_lookaround(Lookbehind, Raw_capture(Raw_con(Raw_empty, Raw_quant(Plus, Raw_capture(Raw_empty))))), "a", Some([0, 0, 0, 0, 0, 0]));
    checkAll(Raw_quant(Plus, Raw_capture(Raw_quant(LazyStar, Raw_empty))), "ccbcbbbbcacbcabbccaaccaccaacacabaacbbbcccbbaabaabccbacccac", Some([0, 0, 0, 0]));
    // cin_examples
    checkAll(Raw_con(Raw_quant(Plus, Raw_alt(Raw_lookaround(Lookahead, Raw_capture(Raw_empty)), Raw_alt(Raw_empty, Raw_character(Char('a'))))), Raw_character(Char('b'))), "b", Some([0, 1, 0, 0]));
    checkAll(Raw_con(Raw_quant(Star, Raw_quant(Plus, Raw_alt(Raw_lookaround(Lookahead, Raw_capture(Raw_empty)), Raw_alt(Raw_empty, Raw_character(Char('a')))))), Raw_character(Char('b'))), "ab", Some([0, 2, -1, -1]));
    checkAll(Raw_con(Raw_quant(Star, Raw_con(Raw_quant(Plus, Raw_alt(Raw_lookaround(Lookahead, Raw_capture(Raw_empty)), Raw_alt(Raw_empty, Raw_character(Char('a'))))), Raw_character(Char('c')))), Raw_character(Char('b'))), "accb", Some([0, 4, 2, 2]));
    // cdn_empty
    checkAll(Raw_quant(Plus, Raw_con(Raw_empty, Raw_lookaround(Lookbehind, Raw_quant(Plus, Raw_lookaround(NegLookbehind, Raw_quant(Plus, Raw_character(Char('c')))))))), "bbaaaacaabaabbbaaacacaacbccbacaacaaaaaabccbbbbbcbcccacabbbaabccccacccabacccacbcbbaacbccbcaacb", Some([0, 0]));
    checkAll(Raw_quant(Plus, Raw_lookaround(Lookbehind, Raw_character(Char('c')))), "ababaaaacbcaababaaccaccacbbbccabbabbcacaa", Some([9, 9]));
    checkAll(Raw_quant(Plus, Raw_lookaround(Lookbehind, Raw_character(Char('b')))), "baabacaccabacabcaaacbbbabacaabbcbbcbaccccaacbacbbababcccbcccacbabababcabbaabacbbbbcaaa", Some([1, 1]));
    checkAll(Raw_lookaround(Lookbehind, Raw_alt(Raw_lookaround(Lookahead, Raw_lookaround(NegLookbehind, Raw_alt(Raw_character(Dot), Raw_empty))), Raw_lookaround(NegLookbehind, Raw_lookaround(NegLookahead, Raw_quant(Plus, Raw_lookaround(Lookahead, Raw_quant(Plus, Raw_empty))))))), "babbccbbabacccabbabccccabacaacacbacabcaaccabbabccaca", Some([0, 0]));
    checkAll(Raw_lookaround(NegLookahead, Raw_quant(Plus, Raw_lookaround(Lookahead, Raw_empty))), "b", None);
    // nullable_expected
    checkAll(Raw_capture(Raw_con(Raw_capture(Raw_quant(Plus, Raw_capture(Raw_quant(Plus, Raw_lookaround(NegLookbehind, Raw_lookaround(NegLookahead, Raw_character(Char('b')))))))), Raw_lookaround(Lookahead, Raw_lookaround(Lookbehind, Raw_character(Dot))))), "caabcbbcbcbcbacacaacbaccabaabbabbcbbbccbbbccac", Some([3, 3, 3, 3, 3, 3, 3, 3]));
    checkAll(Raw_quant(Plus, Raw_quant(Plus, Raw_lookaround(NegLookbehind, Raw_character(Char('b'))))), "cb", Some([0, 0]));
    checkAll(Raw_quant(Plus, Raw_quant(Plus, Raw_lookaround(NegLookbehind, Raw_lookaround(NegLookahead, Raw_empty)))), "caccaacbaabaaabaaacccaacacbbcabbababbacabbabcacabbcaabcbcaaacbabbcccbbcbbbcabbcaccacbacbb", Some([0, 0]));
    checkAll(Raw_con(Raw_lookaround(Lookbehind, Raw_quant(Plus, Raw_quant(Plus, Raw_lookaround(Lookahead, Raw_alt(Raw_capture(Raw_capture(Raw_lookaround(NegLookahead, Raw_character(Char('c'))))), Raw_alt(Raw_character(Dot), Raw_quant(LazyPlus, Raw_capture(Raw_quant(LazyStar, Raw_lookaround(Lookbehind, Raw_character(Char('b')))))))))))), Raw_con(Raw_quant(Plus, Raw_lookaround(Lookahead, Raw_empty)), Raw_character(Char('b')))), "ababcbcaccbbcbbacccbcbccbbabaaaabbbbbabacacbccbabcbbbbabaacabaccabb", Some([1, 2, 1, 1, 1, 1, -1, -1]));
    checkAll(Raw_quant(Plus, Raw_quant(Plus, Raw_lookaround(Lookbehind, Raw_capture(Raw_character(Dot))))), "aaccbcbccccccbbbccccbcbaabbaccbcccaabbacacccabbccaabbcabb", Some([1, 1, 1, 0]));
    checkAll(Raw_lookaround(Lookbehind, Raw_quant(Plus, Raw_quant(Plus, Raw_lookaround(NegLookbehind, Raw_con(Raw_character(Char('a')), Raw_con(Raw_character(Char('b')), Raw_character(Char('b')))))))), "bcaaabccbaabccaaaaababbaaaaaaaaaacbabacabcbbcbbaaabcbbaccabccbcacacc", Some([0, 0]));
    // cdn_formulas
    checkAll(Raw_quant(Plus, Raw_alt(Raw_quant(Plus, Raw_lookaround(Lookahead, Raw_character(Char('a')))), Raw_con(Raw_lookaround(Lookahead, Raw_character(Char('b'))), Raw_lookaround(Lookahead, Raw_character(Char('c')))))), "abc", Some([0, 0]));
    // anchor_context
    checkAll(Raw_lookaround(Lookahead, Raw_anchor(NonWordBoundary)), "cac b", Some([1, 1]));
    checkAll(Raw_alt(Raw_lookaround(Lookbehind, Raw_quant(LazyPlus, Raw_lookaround(Lookahead, Raw_anchor(BeginInput)))), Raw_con(Raw_character(Dot), Raw_lookaround(NegLookahead, Raw_capture(Raw_lookaround(Lookahead, Raw_anchor(BeginInput)))))), "a c b", Some([0, 0, -1, -1]));
    // anchor_cdn
    checkAll(Raw_con(Raw_empty, Raw_quant(Plus, Raw_anchor(BeginInput))), "b  caacaac bcaabc bbcbbaa a  cacccb ab aacccbbb aabbb c bccbcaaaabaa", Some([0, 0]));
    checkAll(Raw_quant(Plus, Raw_anchor(BeginInput)), " cc c  a b acabbbaaaac babaabac bbca bba cccca cacaaabac  ", Some([0, 0]));
    // anchor_mismatch
    checkAll(Raw_con(Raw_capture(Raw_con(Raw_anchor(WordBoundary), Raw_anchor(WordBoundary))), Raw_character(Dot)), "  cab bccbaac baabab bcbbaca cabca  c", Some([2, 3, 2, 2]));
    checkAll(Raw_con(Raw_con(Raw_con(Raw_alt(Raw_capture(Raw_capture(Raw_empty)), Raw_alt(Raw_con(Raw_capture(Raw_character(Dot)), Raw_capture(Raw_alt(Raw_capture(Raw_capture(Raw_capture(Raw_character(Char('a'))))), Raw_capture(Raw_anchor(BeginInput))))), Raw_capture(Raw_quant(Star, Raw_capture(Raw_lookaround(NegLookbehind, Raw_character(Char('c')))))))), Raw_quant(LazyStar, Raw_character(Char(' ')))), Raw_quant(LazyStar, Raw_character(Dot))), Raw_alt(Raw_alt(Raw_lookaround(NegLookahead, Raw_anchor(WordBoundary)), Raw_lookaround(NegLookahead, Raw_empty)), Raw_character(Char('a')))), " abccb ab bb abcaaaa cca cbb a aaccbcab", Some([0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]));
    checkAll(Raw_alt(Raw_alt(Raw_alt(Raw_capture(Raw_quant(Plus, Raw_lookaround(Lookbehind, Raw_con(Raw_character(Dot), Raw_capture(Raw_capture(Raw_character(Dot))))))), Raw_character(Char('a'))), Raw_capture(Raw_capture(Raw_con(Raw_capture(Raw_anchor(WordBoundary)), Raw_quant(Star, Raw_lookaround(Lookahead, Raw_empty)))))), Raw_con(Raw_capture(Raw_empty), Raw_anchor(BeginInput))), " a  b bbc ", Some([0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0]));
    checkAll(Raw_alt(Raw_character(Char('c')), Raw_lookaround(Lookbehind, Raw_con(Raw_anchor(BeginInput), Raw_lookaround(NegLookbehind, Raw_capture(Raw_anchor(WordBoundary)))))), " c  cc bcac c  a a  a  ababab  acbca  cbcb b cccccc cc  a  b  bcbaaaaaaa baaa", Some([0, 0, -1, -1]));
    checkAll(Raw_con(Raw_lookaround(NegLookahead, Raw_capture(Raw_capture(Raw_anchor(NonWordBoundary)))), Raw_character(Dot)), " cc cccc aabaaaa ba abcaabcbbb cacccc  bccbcb cababbabccac ", Some([1, 2, -1, -1, -1, -1]));
    // counted_oob
    checkAll(Raw_alt(Raw_capture(Raw_alt(Raw_anchor(WordBoundary), Raw_capture(Raw_character(Char('b'))))), Raw_count(CountedQuant(5, Some(9), true), Raw_character(Char('a')))), "ab--bbaabab-aab-b-a-aa-b-baa-bab-ba-ab-a--b-ba-a-ab-b--abbbbb-aabbbbba-b-aa---aa-", Some([0, 0, 0, 0, -1, -1]));
    checkAll(Raw_alt(Raw_lookaround(NegLookbehind, Raw_lookaround(Lookbehind, Raw_character(Dot))), Raw_capture(Raw_count(CountedQuant(8, Some(12), true), Raw_lookaround(Lookbehind, Raw_empty)))), "ab-a-aa-a-bb-baaba-a-aabbabaabb-b-aaabaa-ba-", Some([0, 0, -1, -1]));
    checkAll(Raw_count(CountedQuant(3, Some(12), true), Raw_lookaround(Lookbehind, Raw_alt(Raw_quant(LazyPlus, Raw_character(Dot)), Raw_alt(Raw_count(CountedQuant(4, None, true), Raw_anchor(BeginInput)), Raw_con(Raw_lookaround(Lookbehind, Raw_alt(Raw_con(Raw_count(CountedQuant(8, None, true), Raw_con(Raw_capture(Raw_character(Char('a'))), Raw_alt(Raw_capture(Raw_count(CountedQuant(5, Some(5), false), Raw_quant(Plus, Raw_alt(Raw_anchor(WordBoundary), Raw_lookaround(NegLookahead, Raw_lookaround(NegLookahead, Raw_empty)))))), Raw_capture(Raw_empty)))), Raw_empty), Raw_character(Char('-')))), Raw_anchor(WordBoundary)))))), "a", Some([0, 0, -1, -1, -1, -1, -1, -1]));
    checkAll(Raw_lookaround(Lookbehind, Raw_alt(Raw_quant(Plus, Raw_anchor(BeginInput)), Raw_quant(Plus, Raw_character(Char('a'))))), "a", Some([0, 0]));
    checkAll(Raw_lookaround(Lookahead, Raw_alt(Raw_count(CountedQuant(1, Some(3), true), Raw_character(Dot)), Raw_empty)), "a-abb-bbbb----bbaa--aabb-abaab---b-bab-b--ba--a--bb-babb-b", Some([0, 0]));
    checkAll(Raw_count(CountedQuant(4, Some(8), false), Raw_character(Dot)), "abbb--a-ab-aa--ba--bb-aaa", Some([0, 4]));
    // regs_mismatch
    checkAll(Raw_alt(Raw_count(CountedQuant(3, None, true), Raw_alt(Raw_con(Raw_empty, Raw_capture(Raw_alt(Raw_alt(Raw_quant(Star, Raw_character(Dot)), Raw_character(Dot)), Raw_capture(Raw_anchor(WordBoundary))))), Raw_quant(LazyStar, Raw_count(CountedQuant(7, None, true), Raw_empty)))), Raw_count(CountedQuant(8, Some(15), true), Raw_lookaround(Lookahead, Raw_anchor(EndInput)))), "a", Some([0, 1, 1, 1, -1, -1]));
    checkAll(Raw_quant(Plus, Raw_capture(Raw_character(Char('a')))), "ab--bbb---ba-b-b--abababbaabab--b-", Some([0, 1, 0, 1]));
    // regs_oob
    checkAll(Raw_con(Raw_capture(Raw_quant(Star, Raw_capture(Raw_capture(Raw_lookaround(Lookahead, Raw_character(Char('b'))))))), Raw_capture(Raw_anchor(BeginInput))), "-baba-aa-bb-a-bba", Some([0, 0, 0, 0, -1, -1, -1, -1, 0, 0]));
    checkAll(Raw_capture(Raw_con(Raw_capture(Raw_alt(Raw_alt(Raw_count(CountedQuant(9, Some(13), true), Raw_capture(Raw_count(CountedQuant(3, Some(7), false), Raw_capture(Raw_lookaround(Lookahead, Raw_character(Dot)))))), Raw_con(Raw_character(Char('b')), Raw_empty)), Raw_con(Raw_character(Dot), Raw_con(Raw_character(Char('b')), Raw_con(Raw_count(CountedQuant(2, Some(10), false), Raw_quant(LazyQuestionMark, Raw_lookaround(Lookbehind, Raw_con(Raw_lookaround(Lookahead, Raw_character(Char('a'))), Raw_capture(Raw_lookaround(NegLookahead, Raw_empty)))))), Raw_anchor(NonWordBoundary)))))), Raw_capture(Raw_count(CountedQuant(4, Some(10), true), Raw_quant(QuestionMark, Raw_anchor(NonWordBoundary)))))), "--a-bb-aa--a-a", Some([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0]));
    checkAll(Raw_capture(Raw_alt(Raw_lookaround(Lookbehind, Raw_count(CountedQuant(9, None, true), Raw_lookaround(Lookahead, Raw_alt(Raw_capture(Raw_capture(Raw_empty)), Raw_lookaround(NegLookbehind, Raw_character(Dot)))))), Raw_capture(Raw_capture(Raw_empty)))), "----bb-a-ab", Some([0, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1, -1]));
    checkAll(Raw_capture(Raw_capture(Raw_anchor(BeginInput))), "--aa---a-a----baabb--b-aa--aabba-bb-aa-b---aba-a-abbaab-b-", Some([0, 0, 0, 0, 0, 0]));
    // start_no_end
    checkAll(Raw_alt(Raw_anchor(EndInput), Raw_quant(LazyPlus, Raw_capture(Raw_lookaround(NegLookahead, Raw_con(Raw_capture(Raw_anchor(WordBoundary)), Raw_character(Dot)))))), "b", Some([1, 1, -1, -1, -1, -1]));
    checkAll(Raw_alt(Raw_character(Char('-')), Raw_capture(Raw_con(Raw_lookaround(Lookbehind, Raw_empty), Raw_lookaround(NegLookahead, Raw_character(Dot))))), "babb-bab-aabb-bb-abbabababaaa-abaab--b-bbb-b-", Some([4, 5, -1, -1]));
    // class_next_char
    checkAll(Raw_character(Class([CGroup(NonWord), CChar('-'), CChar('b'), CRange((168 as char), (246 as char)), CGroup(Word), CChar('a')])), "a", Some([0, 1]));
    // class_negation
    checkAll(Raw_capture(Raw_character(NegClass([CRange('f', (183 as char)), CRange('U', (231 as char)), CChar('a'), CGroup(NonWord), CRange((149 as char), (251 as char)), CChar('-'), CGroup(Digit), CChar('b'), CChar('b'), CGroup(NonWord), CGroup(NonWord), CRange((151 as char), (245 as char)), CGroup(NonWord), CRange((198 as char), (213 as char)), CChar('-')]))), "b", None);
    checkAll(Raw_character(NegClass([CGroup(NonWord)])), "b", Some([0, 1]));
    // class_escape
    checkAll(Raw_character(Class([CChar('b'), CChar('-'), CChar('b'), CRange((243 as char), (244 as char)), CGroup(Word), CGroup(Space)])), "-baabbbb--ab-aab-baba-bab-a-aaaaa-baa--aaaaa-ab--a-baabb--abb-bb-aab--", Some([0, 1]));
    // js_export_bug
    checkAll(Raw_alt(Raw_lookaround(Lookahead, Raw_character(Group(Digit))), Raw_lookaround(Lookahead, Raw_capture(Raw_character(NegClass([CGroup(Space), CGroup(NonWord), CRange((12 as char), (233 as char)), CRange((255 as char), (255 as char)), CRange('+', (212 as char)), CRange((229 as char), (249 as char)), CGroup(Space), CRange((27 as char), (254 as char)), CGroup(Digit), CRange((0 as char), (151 as char)), CChar('b'), CGroup(Word), CRange((129 as char), (207 as char)), CChar('b'), CChar('a'), CGroup(Word)]))))), "a", None);
    checkAll(Raw_character(NegClass([CRange((0 as char), (151 as char))])), "a", None);
    checkAll(Raw_character(NegClass([CRange((92 as char), (238 as char)), CChar('a'), CChar('-'), CRange('v', (193 as char)), CChar('a'), CGroup(NonWord)])), "a-a-aba---aaabbb--a-baabbabbaa-a-aab--bba", None);
    checkAll(Raw_character(NegClass([CRange((92 as char), 'x')])), "b", None);
    checkAll(Raw_character(Class([CGroup(Digit), CRange('7', (195 as char)), CRange((239 as char), (254 as char)), CRange('P', (166 as char)), CRange('m', (250 as char)), CGroup(Digit), CChar('-'), CChar('a'), CGroup(NonSpace), CGroup(Digit), CRange((190 as char), (196 as char)), CRange('S', 'Y'), CGroup(Digit), CRange('+', '@'), CRange((7 as char), ']'), CRange((2 as char), (205 as char)), CRange((146 as char), (166 as char)), CChar('b'), CRange((195 as char), (205 as char))])), "-b---abba-baab----a-abaabb----aa--b--b-abba-a-a--b-b-bb-a--aa-bbbaaab--aaaaaab", Some([0, 1]));
    checkAll(Raw_character(Class([CGroup(NonSpace), CRange((7 as char), ']')])), "-", Some([0, 1]));
    checkAll(Raw_character(Class([CChar('b'), CRange((242 as char), (252 as char)), CRange((39 as char), (223 as char)), CRange((200 as char), (239 as char)), CGroup(Digit), CRange((234 as char), (242 as char)), CRange((230 as char), (254 as char)), CGroup(NonDigit), CGroup(Space), CGroup(Digit)])), "-babbababb-b--aaaaa-aaa-bab-b--", Some([0, 1]));
    // empty_bytecode
    checkAll(Raw_capture(Raw_lookaround(Lookahead, Raw_quant(Plus, Raw_count(CountedQuant(9, Some(10), false), Raw_anchor(NonWordBoundary))))), "-b-a--b-bababbaab-ba-aa--bb-a-bb-aaab-aababba---a-b-bbb-ab--ba-a-a-bba-ba-a--ba-ababb--baab-b--ba", Some([0, 0, 0, 0]));
    checkAll(Raw_capture(Raw_lookaround(Lookahead, Raw_quant(Plus, Raw_count(CountedQuant(1, None, false), Raw_anchor(NonWordBoundary))))), "-b", Some([0, 0, 0, 0]));
    // cin_clock_mismatch
    checkAll(Raw_count(CountedQuant(9, None, true), Raw_count(CountedQuant(9, Some(13), true), Raw_alt(Raw_character(Char('a')), Raw_capture(Raw_alt(Raw_anchor(NonWordBoundary), Raw_empty))))), "aabaaaabbaabb-aa-a-a-baba-bb-baba-a-abbaabaa", Some([0, 2, 2, 2]));
    checkAll(Raw_count(CountedQuant(2, None, true), Raw_count(CountedQuant(2, Some(2), true), Raw_capture(Raw_empty))), "a", Some([0, 0, 0, 0]));
    checkAll(Raw_count(CountedQuant(2, None, true), Raw_count(CountedQuant(2, Some(2), true), Raw_alt(Raw_character(Char('a')), Raw_capture(Raw_empty)))), "a", Some([0, 1, 1, 1]));
    // lazy_cin
    checkAll(Raw_con(Raw_quant(LazyPlus, Raw_capture(Raw_quant(LazyStar, Raw_quant(LazyPlus, Raw_quant(LazyPlus, Raw_quant(LazyPlus, Raw_quant(QuestionMark, Raw_quant(LazyPlus, Raw_character(Dot))))))))), Raw_character(Char('a'))), "b--b-ab-bb--bbbaaa--bbabab-aab-a-bb-a-abbb-bbbaa--bbabb--ba--bbab--aabb---ab-----bbb-bbbba--", Some([0, 6, 4, 5]));
    checkAll(Raw_con(Raw_quant(LazyPlus, Raw_capture(Raw_quant(LazyStar, Raw_character(Dot)))), Raw_character(Char('a'))), "b-a", Some([0, 3, 1, 2]));
    // redos
    checkAll(Raw_lookaround(Lookbehind, Raw_con(Raw_lookaround(NegLookahead, Raw_character(Dot)), Raw_quant(LazyPlus, Raw_capture(Raw_con(Raw_quant(Star, Raw_character(Char('a'))), Raw_con(Raw_alt(Raw_empty, Raw_character(Dot)), Raw_character(Dot))))))), "cbabbccccbbcccaaaaaccabccbaabaabcaaacbca", None);
    checkAll(Raw_con(Raw_con(Raw_lookaround(Lookahead, Raw_capture(Raw_capture(Raw_character(Dot)))), Raw_capture(Raw_alt(Raw_lookaround(Lookahead, Raw_character(Dot)), Raw_alt(Raw_con(Raw_capture(Raw_quant(Star, Raw_character(Char('c')))), Raw_capture(Raw_character(Char('a')))), Raw_alt(Raw_capture(Raw_quant(Plus, Raw_quant(Plus, Raw_lookaround(Lookahead, Raw_empty)))), Raw_capture(Raw_alt(Raw_alt(Raw_lookaround(NegLookbehind, Raw_quant(LazyPlus, Raw_capture(Raw_alt(Raw_con(Raw_capture(Raw_character(Dot)), Raw_lookaround(Lookbehind, Raw_capture(Raw_con(Raw_capture(Raw_capture(Raw_alt(Raw_character(Char('a')), Raw_quant(LazyPlus, Raw_con(Raw_lookaround(NegLookbehind, Raw_quant(LazyPlus, Raw_lookaround(Lookahead, Raw_empty))), Raw_quant(Plus, Raw_alt(Raw_character(Dot), Raw_capture(Raw_capture(Raw_character(Dot)))))))))), Raw_empty)))), Raw_lookaround(Lookahead, Raw_character(Char('c'))))))), Raw_character(Dot)), Raw_character(Dot)))))))), Raw_con(Raw_alt(Raw_con(Raw_alt(Raw_capture(Raw_quant(LazyStar, Raw_con(Raw_capture(Raw_character(Char('b'))), Raw_alt(Raw_empty, Raw_character(Char('c')))))), Raw_character(Dot)), Raw_character(Dot)), Raw_lookaround(NegLookbehind, Raw_lookaround(Lookbehind, Raw_lookaround(NegLookbehind, Raw_empty)))), Raw_lookaround(NegLookahead, Raw_alt(Raw_alt(Raw_capture(Raw_capture(Raw_empty)), Raw_lookaround(Lookbehind, Raw_empty)), Raw_lookaround(Lookahead, Raw_empty))))), "ccaacababbbcccbbbabcbbbccaaabccacbcb", None);
    checkAll(Raw_capture(Raw_alt(Raw_alt(Raw_con(Raw_alt(Raw_lookaround(NegLookbehind, Raw_con(Raw_con(Raw_alt(Raw_quant(Star, Raw_lookaround(Lookahead, Raw_capture(Raw_lookaround(Lookahead, Raw_capture(Raw_lookaround(Lookbehind, Raw_capture(Raw_empty))))))), Raw_empty), Raw_alt(Raw_character(Char('a')), Raw_capture(Raw_quant(LazyPlus, Raw_lookaround(Lookahead, Raw_con(Raw_con(Raw_capture(Raw_alt(Raw_quant(Plus, Raw_capture(Raw_capture(Raw_capture(Raw_character(Char('a')))))), Raw_character(Char('b')))), Raw_empty), Raw_lookaround(Lookbehind, Raw_con(Raw_con(Raw_alt(Raw_capture(Raw_lookaround(Lookbehind, Raw_capture(Raw_con(Raw_lookaround(NegLookbehind, Raw_character(Dot)), Raw_empty)))), Raw_quant(LazyPlus, Raw_con(Raw_character(Dot), Raw_quant(Star, Raw_alt(Raw_con(Raw_lookaround(NegLookahead, Raw_lookaround(Lookbehind, Raw_character(Char('a')))), Raw_capture(Raw_character(Dot))), Raw_capture(Raw_con(Raw_lookaround(NegLookahead, Raw_quant(LazyStar, Raw_empty)), Raw_capture(Raw_character(Char('c')))))))))), Raw_character(Char('b'))), Raw_empty)))))))), Raw_lookaround(NegLookahead, Raw_con(Raw_capture(Raw_character(Char('a'))), Raw_con(Raw_empty, Raw_lookaround(Lookahead, Raw_quant(Star, Raw_character(Char('c'))))))))), Raw_alt(Raw_con(Raw_con(Raw_alt(Raw_lookaround(Lookbehind, Raw_capture(Raw_lookaround(Lookbehind, Raw_character(Dot)))), Raw_con(Raw_con(Raw_capture(Raw_lookaround(NegLookbehind, Raw_character(Char('b')))), Raw_quant(LazyPlus, Raw_quant(Star, Raw_quant(LazyStar, Raw_alt(Raw_capture(Raw_capture(Raw_capture(Raw_capture(Raw_character(Dot))))), Raw_character(Dot)))))), Raw_capture(Raw_capture(Raw_character(Char('c')))))), Raw_con(Raw_lookaround(NegLookahead, Raw_quant(Plus, Raw_capture(Raw_character(Char('b'))))), Raw_capture(Raw_alt(Raw_con(Raw_character(Dot), Raw_quant(Star, Raw_character(Char('b')))), Raw_quant(Plus, Raw_lookaround(Lookbehind, Raw_lookaround(NegLookbehind, Raw_con(Raw_lookaround(NegLookahead, Raw_quant(Plus, Raw_character(Char('c')))), Raw_character(Dot))))))))), Raw_quant(Plus, Raw_empty)), Raw_quant(Plus, Raw_empty))), Raw_lookaround(Lookahead, Raw_capture(Raw_lookaround(NegLookbehind, Raw_empty)))), Raw_character(Char('b'))), Raw_character(Char('b')))), "acccbcabbacbccbccbbcbbaa", Some([4, 5, 4, 5, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]));
    checkAll(Raw_con(Raw_alt(Raw_character(Char('a')), Raw_con(Raw_quant(LazyStar, Raw_capture(Raw_quant(Star, Raw_alt(Raw_character(Dot), Raw_quant(Plus, Raw_empty))))), Raw_alt(Raw_character(Char('b')), Raw_lookaround(NegLookahead, Raw_empty)))), Raw_con(Raw_lookaround(NegLookahead, Raw_capture(Raw_character(Dot))), Raw_capture(Raw_capture(Raw_capture(Raw_character(Dot)))))), "cabbcaacbaccccababcbcccbababacbcccabbaaacacacbcacccaaacbbccabaabbaacbcbcacaaacabaacaaaa", None);
    // paper_tests
    checkAll(Raw_con(Raw_quant(Star, Raw_character(Char('a'))), Raw_character(Char('b'))), "caabd", Some([1, 4]));
    checkAll(Raw_capture(Raw_alt(Raw_character(Char('a')), Raw_quant(Star, Raw_character(Char('a'))))), "aa", Some([0, 1, 0, 1]));
    checkAll(Raw_con(Raw_lookaround(Lookbehind, Raw_character(Char('L'))), Raw_character(Char('1'))), "L1.2", Some([1, 2]));
    checkAll(Raw_con(Raw_lookaround(Lookbehind, Raw_character(Char('L'))), Raw_character(Char('1'))), "v1.2", None);
    checkAll(Raw_con(Raw_lookaround(Lookbehind, Raw_con(Raw_con(Raw_con(Raw_character(Char('P')), Raw_character(Char('L'))), Raw_character(Char('D'))), Raw_character(Char('I')))), Raw_count(CountedQuant(2, Some(4), true), Raw_character(Class([CRange('0', '9')])))), "PLDI2024", Some([4, 8]));
    checkAll(Raw_con(Raw_capture(Raw_alt(Raw_character(Char('a')), Raw_character(Dot))), Raw_character(Char('b'))), "ab", Some([0, 2, 0, 1]));
    checkAll(Raw_con(Raw_quant(Star, Raw_capture(Raw_quant(Plus, Raw_character(Char('a'))))), Raw_character(Char('b'))), "aaa", None);
    checkAll(Raw_lookaround(Lookahead, Raw_capture(Raw_character(Char('c')))), "c", Some([0, 0, 0, 1]));
    checkAll(Raw_quant(Star, Raw_capture(Raw_alt(Raw_capture(Raw_character(Char('a'))), Raw_capture(Raw_character(Char('b')))))), "ab", Some([0, 2, 1, 2, -1, 1, 1, 2]));
    checkAll(Raw_quant(Star, Raw_con(Raw_alt(Raw_character(Char('a')), Raw_empty), Raw_alt(Raw_empty, Raw_character(Char('b'))))), "ab", Some([0, 2]));
    checkAll(Raw_count(CountedQuant(0, Some(7), true), Raw_con(Raw_alt(Raw_character(Char('a')), Raw_empty), Raw_alt(Raw_empty, Raw_character(Char('b'))))), "ab", Some([0, 2]));
    checkAll(Raw_quant(Star, Raw_alt(Raw_quant(Star, Raw_alt(Raw_capture(Raw_character(Char('a'))), Raw_character(Char('b')))), Raw_character(Char('c')))), "ac", Some([0, 2, -1, 1]));
    checkAll(Raw_quant(Star, Raw_alt(Raw_quant(Star, Raw_capture(Raw_character(Char('a')))), Raw_quant(Star, Raw_alt(Raw_capture(Raw_character(Char('b'))), Raw_capture(Raw_character(Char('c'))))))), "abc", Some([0, 3, -1, 1, -1, 2, 2, 3]));
    checkAll(Raw_con(Raw_con(Raw_con(Raw_character(Char('a')), Raw_character(Char('b'))), Raw_character(Char('c'))), Raw_lookaround(Lookbehind, Raw_con(Raw_con(Raw_con(Raw_character(Char('a')), Raw_character(Char('b'))), Raw_lookaround(Lookbehind, Raw_character(Char('b')))), Raw_character(Char('c'))))), "abc", Some([0, 3]));
    checkAll(Raw_quant(Plus, Raw_alt(Raw_empty, Raw_character(Dot))), "a", Some([0, 1]));
    checkAll(Raw_con(Raw_quant(Star, Raw_quant(Star, Raw_character(Char('a')))), Raw_lookaround(Lookahead, Raw_character(Char('b')))), "aaaaaaaaaaaaaa", None);
    print "OCaml bug-regression cross-check: all cases match the OCaml engine across Array/List/Map\n";
  }
}
